# Generated by Django 4.2.3 on 2023-07-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='telefono',
            field=models.TextField(),
        ),
    ]
